### PR TITLE
Install python2 dependencies into virtualenv

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Create virtualenv and install dependencies into it.  Also refactor to remove all cache handling from cmake; it's saved and restored entirely by the jenkins-build scripts.  (We can move it into the cmake logic entirely in the future.)  This was needed because virtualenvs are not relocatable, unlike all the other cached files.

This updates sphinx to the latest version, as well as simplifying python dependency installation in general.

Testing: Check that the superbuild jobs are green twice in a row.  First to cache the dependencies, second to use the cached dependencies and only build gtest/ome-common/model/files/...

- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-superbuild/
- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-win-superbuild/

### CODE REVIEW

**Comment by sbesson** [comment]
A few high-level questions on the nature of the changes and the overall impact:

- in the context of the [CI documentation jobs](https://trello.com/c/ccx2knE7/528-check-whether-sphinx-can-be-upgraded-for-all-docs-jobs), if a Python dependency like Sphinx is installed globally, will it get picked up or is it systematically reinstalled by the superbuild infrastructure?
- for Python 2.6 vs Python 2.7 environments (C6/C7), does this infrastructure handle multiple versions of Sphinx or are we effectively setting Python 2.7 via the `python2-virtualenv` dependency?
- more generally, is this PR effectively proposing `python2-virtualenv` as a new base requirement? If this is the case, I assume there will be a few places to review incl. our CI infrastructure, the Docker base image, the documentation. Is there a list of all places to review?

**Comment by rleigh-codelibre** [comment]
- For this case, if third-party dependencies are enabled, then you get sphinx via the superbuild virtualenv with the system copy being ignored entirely (if present), so it's uniform across all superbuild jobs.
- We always get Python 2.7 (we already use SCL Python 2.7 on CentOS6/gretzky35)
- Python 2.7 virtualenv would become a base requirement.  It's already present everywhere, but on Ubuntu there's a distinction between `virtualenv` (the command) and `python-virtualenv` (the module).  We use the latter because it works on all systems uniformly but the command isn't guaranteed to.  We can add this to the ansible roles etc.

**Comment by sbesson** [comment]
Thanks @rleigh-codelibre. I have not assessed all of the potential implications of switching the Python dependency strategy but at the documentation level this seems to have fixed the [builds](https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-docs/BUILD_TYPE=Release,node=marlin/538/consoleText) which is a good step forward.

Once we have confirmed this strategy works across all supported platforms and agreed on using it, these changes will also need to be propagated to the Sphinx documentation.

**Comment by rleigh-codelibre** [comment]
The pip failure on Windows is now fixed.  The builds should all go green, and a second build should confirm if the virtualenv works with the build caching.

**Comment by dgault** [comment]
Both the builds have been green for 2 consecutive runs. Looking through the logs shows that the first run adds and installs the dependencies while the second run uses the cached dependencies. From that perspective the PR appears to be working as expected.

**Comment by joshmoore** [comment]
@rleigh-codelibre : have you looked into what documentation changes are needed for this?

**Comment by rleigh-codelibre** [comment]
The only change is the requirement for virtualenv to be installed, which I'll add.

**Comment by rleigh-codelibre** [comment]
@joshmoore Documentation updated.  Run `make html` in `docs/sphinx` to check it; it updates the python package pages.

**Comment by joshmoore** [comment]
Docs reviewed locally. Thanks.

For my own information: Does the necessity for virtualenv (or the installation of requirements) propagate to any of the other repos? What requirements files are in play here?

NB:

> This was needed because virtualenvs are not relocatable, unlike all the other cached files.

Did you try with the experimental `--relocatable` option?

**Comment by rleigh-codelibre** [comment]
The relocatable option is certainly something to look at for the future.  But it's likely easier not to move it around by creating it in the cached location to start with.

The virtualenv requirement is purely for superbuild use when installing third-party prerequisites.  All other components work independently of whether they are using a virtualenv or not at a higher level.

**Comment by joshmoore** [comment]
_Alles klar_ Merging and progressing with 0.5.0

**Pull request merged**
