### PR TITLE
jenkins-build: Add batch file for Windows and support Ninja build system

### PR DESCRIPTION
**Pull request by ghost**
Add `scripts/jenkins-build.bat`.  This is the Windows equivalent to the previously added `scripts/jenkins-build` shell script.  The batch file behaves identically to the shell script, implementing the same options and caching behaviour.  A few Windows-specific options are added in addition.

Testing: The Windows superbuild job will be updated to use the batch file, replacing the logic in the job.

Check https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/29/ and later builds.

```
if [%VSCONFIG%] == [Debug] set EXTENDED_TESTS=-e
if [%VERBOSE%] == [true] set CMAKE_VERBOSE=-v

call superbuild\scripts\jenkins-build %EXTENDED_TESTS% %CMAKE_VERBOSE% -w "%WORKSPACE%" -s "%WORKSPACE%\superbuild" -G -g "scc/%PUSH_BRANCH%" -p %PURGE_CACHE% -t %VSCONFIG% -A %VSARCH% -V %VSVERSION% -S %BUILD_SYSTEM% -j 12 || exit /b
```

The Unix jenkins-build script will now support builds without third-party prerequisites.  See https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge/BUILD_TYPE=Release,node=cod/1/ and later builds.

Both the Unix and Windows scripts now also support an `-S Ninja` option to build with `ninja` in place of make or msbuild.  This allows faster builds due to supporting much better parallelisation.  The Windows maxquant node will benefit greatly from this; the other nodes may also, but most are already too constrained to run much in parallel.

After fixing boost to build with Ninja (in #23), I've enabled this as a test.  See https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/34/  Note that this also reduces the log size, since Ninja is much terser than msbuild.  See the build time reduction here: https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/buildTimeTrend

Also see https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/42/consoleText for cowfish.  Build time reduced to 13 mins (with caching): https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/buildTimeTrend .

### CODE REVIEW

**Comment by sbesson** [comment]
Generally, as for https://github.com/ome/ome-cmake-superbuild/pull/18, big thumbs up  for migrating the Jenkins Windows build logic as a script in this repository. This should greatly simplify the review of future code changes coupled with build changes. Last builds of https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild are green with this PR included and the build time is reduced as described.

Reading through the changes and the PR description, it raises an important question about our build strategy in the near future. Are we migrating to `ninja` as the default build system across the board (Unix and Windows) as suggested in the PR description? If so should we drop `make/msbuild` or will we support multiple build systems and do we need to have each build system as a matrix component?

Along with other features opened as separate PRs (C++/Boost), let us schedule some time to discuss these proposals early in 2016. /cc @joshmoore

**Comment by ghost** [comment]
@sbesson No, we won't be migrating to ninja wholesale; we'll need to support both.  If you want to integrate our stuff directly into Visual Studio, the msbuild generator generates the solution and project files to do so.  The ninja build is just for building with vastly greater speed.  Ideally, it would be good to test both, but jenkins isn't great at randomly flipping options, so we might need to e.g. retain msbuild for the -latest builds.  While we could have this as a matrix component, the primary intent is to reduce build time, which wouldn't happen if we build both.

We could also use it for the Unix builds, but make is the expected standard so we would need to continue to support that; cmake supports both so essentially we get both for free; we just need to avoid logic which would break one or the other.  On the jenkins side, the issue is that the build nodes like cod and perch simply don't have the resources to effectively parallelise the builds, so both make and ninja need to avoid running jobs in parallel or else they fail.  On Unix there's no practical speed advantage, but we could e.g. selectively enable it on cowfish, which does have the capacity to handle parallel builds.  If we get nodes running inside docker, these could also potentially benefit from the parallelisation.

**Comment by ghost** [comment]
Don't merge this just yet.  I found a tweak is needed to build the full package set on Unix with Ninja, which I'll make shortly.

**Comment by joshmoore** [comment]
Merging the unfortunately tangled but thankfully green:
- https://github.com/ome/ome-cmake-superbuild/pull/26
- https://github.com/ome/ome-cmake-superbuild/pull/27
- https://github.com/openmicroscopy/bioformats/pull/2169
- https://github.com/ome/ome-cmake-superbuild/pull/28
- https://github.com/ome/ome-cmake-superbuild/pull/29

based on:
- https://ci.openmicroscopy.org/view/CPP/job/BIOFORMATS-CPP-DEV-merge/34/
- https://ci.openmicroscopy.org/view/CPP/job/BIOFORMATS-CPP-DEV-merge-superbuild/64/
- https://ci.openmicroscopy.org/view/CPP/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/66/

**Pull request merged**
