### PR TITLE
jenkins-build: Add 'platform' or 'standalone' to bundle name

### PR DESCRIPTION
**Pull request by ghost**
platform: No third-party prerequisites, built against platformlibraries
standalone: Contains and is built against all needed third-party libraries

Previously, we had to store these in separate directories and the fact that we had the different artefacts with the same name was ambigious.  This makes it explicit what is contained, and also simplifies the release jobs and download page generation.

---

Testing: You'll see a difference in the binary build names between the regular merge build and the superbuild; the Windows builds are unchanged (they are always standalone, so no need to qualify the name).

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/lastSuccessfulBuild/artifact/artefacts/superbuild/

**Comment by ghost** [comment]
Examples of the naming and structure to be copied directly to the download directory:

https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/lastSuccessfulBuild/artifact/artefacts/
https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge/BUILD_TYPE=Debug,node=marlin/lastSuccessfulBuild/artifact/artefacts/

**Comment by joshmoore** [comment]
re: naming -- this seems to speak for the use of the name "bundle" since "package" and "superbuild" clearly bind more tightly with "bundle" then the rest.

**Comment by dgault** [comment]
Comparing the latest merge and superbuilds, and the naming changes have certainly been applied as expected.

I am happy enough with the naming of platform and standalone and they they so make sense, so as long as there is no veto on the naming the changes look good to me.

**Comment by ghost** [comment]
@sbesson Please could this be merged?

**Comment by sbesson** [comment]
Thanks @rleigh-dundee. Merging let let a first version of the release be produced.

**Pull request merged**
