### PR TITLE
Revert absolute path usage for glm build

### PR DESCRIPTION
**Pull request by ghost**
- revert absolute path usage
- remove glm

Since we're not supporting Qt for this release, the glm removal is fine.  The relative path usage fixes "bf-test" for 5.1.6.  Since the glm and absolute path changes are merged to develop, we can fix the "bf-test" tool on develop to work properly with absolute paths.

Needed for 5.1.6.

---

Testing: Download any of the UNIX build tar.xz files, unpack, and run /path/to/unpacked-release/bin/bf-test with the options "--help" or "info /path/to/some/ome.tiff".  Both should work.

### CODE REVIEW

**Comment by mtbc** [comment]
I don't know if https://ci.openmicroscopy.org/view/CPP/job/BIOFORMATS-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/lastSuccessfulBuild/artifact/install/ is a reasonable place to look for these UNIX build tar.xz files but they seem to be tarred up with a full `/opt/hudson/workspace/BIOFORMATS-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/cowfish/` path in the archive; I do have the right artifacts? (Now to try out a CentOS 7 docker image!)

**Comment by sbesson** [comment]
@mtbc I think you want to test this PR with https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/ job which is currently running.

**Comment by mtbc** [comment]
Oh, doh, yes, 5.1, thanks. I wonder if that will have the same enormous path. (I also wonder if the vanilla docker CentOS 7 image will work or if I should be trying something from https://github.com/snoopycrimecop/omero-install/tree/merge/master/latest to help with reviewing https://github.com/ome/omero-install/pull/56.)

**Comment by mtbc** [comment]
Ah, looks like that job will take ages yet. (I'll probably skip trying to take this today then given my unfamiliarity with other aspects too; I'll take https://github.com/ome/ome-cmake-superbuild/pull/16 instead.)

**Comment by ghost** [comment]
I think that should be fixed, but if not it may require picking up any missing changes from the -merge jobs.

**Comment by ghost** [comment]
@sbesson One thing which isn't happening here is a daily trigger for the jobs.  I've triggered it by hand today, but it would be useful to automate as for the 5.1 jobs (I think possibly they get triggered there by the java merge job, but given the splitting, would be nice to make independent here).

**Comment by joshmoore** [comment]
Using https://ci.openmicroscopy.org/view/CPP/job/BIOFORMATS-CPP-5.1-merge-superbuild/BUILD_TYPE=Release,CXXSTD_AUTODETECT=ON,node=gretzky35/155/

I get:

```
[bf@09babdae4d51 bioformats-cpp-5.1.6-18-g946649b-Release-CentOS6.6-x86_64]#  /foo/bioformats-cpp-5.1.6-18-g946649b-Release-CentOS6.6-x86_64/opt/hudson/workspace/BIOFORMATS-CPP-5.1-merge-superbuild/BUILD_TYPE/Release/CXXSTD_AUTODETECT/ON/node/gretzky35/install/bin/bf-test  info
/foo/bioformats-cpp-5.1.6-18-g946649b-Release-CentOS6.6-x86_64/opt/hudson/workspace/BIOFORMATS-CPP-5.1-merge-superbuild/BUILD_TYPE/Release/CXXSTD_AUTODETECT/ON/node/gretzky35/install/libexec/info: error while loading shared libraries: libboost_program_options-mt.so.1.53.0: cannot open shared object file: No such file or directory
```

**Comment by ghost** [comment]
Likely needs the job adjusting then; works fine building by hand.

**Comment by ghost** [comment]
@joshmoore I've adjusted the job and restarted it.

**Comment by ghost** [comment]
@joshmoore Green in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-5.1-merge-superbuild/156/ and the archive pathnames are correct, and bf-test works as expected.  If you could possibly verify this and merge the PR, I can then double-check the release job and re-run it.  Thanks.

**Comment by joshmoore** [comment]
```
~/tmp $ docker run -ti --rm -u 1000 -v `pwd`/bioformats-cpp-5.1.6-20-g003bbfa-Release-CentOS6.6-x86_64:/cpp centos:centos6
bash-4.1$ cd /cpp
bash-4.1$ bin/bf-test info -h
/cpp/libexec/info: error while loading shared libraries: libboost_program_options-mt.so.1.53.0: cannot open shared object file: No such file or directory
```

**Comment by ghost** [comment]
@joshmoore Does it work with `./bin/bf-test info` ?  Both work for me with the MacOSX10.11 build.

**Comment by ghost** [comment]
@joshmoore Actually, I think the issue here is that it's linked against the system boost rather than the superbuild boost.  You're definitely testing the merge-superbuild build rather than the regular merge build?

**Comment by joshmoore** [comment]
I used the same link as above (https://ci.openmicroscopy.org/view/CPP/job/BIOFORMATS-CPP-5.1-merge-superbuild/BUILD_TYPE=Release,CXXSTD_AUTODETECT=ON,node=gretzky35/155/) but incremented the build number.

**Comment by ghost** [comment]
@joshmoore Found the problem.  Due to the caching for performance, it's not putting the cached content into the archive; that's a needed job change.  This won't be an issue for the release job.  The other issue is that it's not linking against the cached boost; looks like another issue with the job.  I don't think either are problems with the PR itself though.

**Comment by joshmoore** [comment]
Are you looking into the job or should someone else?

**Comment by ghost** [comment]
I can look at it this evening.  I think it would be best to move the jenkins logic into a shell script in the repo--the turnaround time testing the jenkins logic on the build nodes is too high, with the caching this becomes a multi-day endevour, and having it as a script makes it properly testable outside jenkins.

That said, this need not block doing the release since the release jobs will be unaffected.  If you build this by hand it should work just fine.  If you want to merge this now and fix the job later, that's doable.  If you'd prefer to merge once the job is fixed and release after that, that's fine, but will take another few days to test the jobs after they are fixed.

**Comment by joshmoore** [comment]
Sorry, based on the complexity, I don't feel comfortable until this is passing. Big :thumbsup: to having the build script logic in the repo itself. Should make all this vastly more manageable.

**Comment by ghost** [comment]
@joshmoore Current work is here: https://github.com/ome/ome-cmake-superbuild/compare/dev_5_1...rleigh-dundee:build-script?expand=1  Mostly done, I found some additional issues with CentOS6 which this resolves, but needs more testing before I open a PR for it and adjust the job to use it.

**Comment by ghost** [comment]
Closing in favour of https://github.com/ome/ome-cmake-superbuild/pull/18

**Comment by ghost** [comment]
--rebased-to #23

**Pull request closed without merging**
