### PR TITLE
Backport superbuild changes from develop

### PR DESCRIPTION
**Pull request by ghost**
- brings all bugfixes and improvements since dev_5_1 was branched, including
- Ninja support
- VS2012 now compiles [untested on 5.1]
- jenkins-build scripts
- improved build caching
- boost 1.60
- improved job options to select the components to build, including the bioformats repo/directory

This will
- allow use of Ninja on the Windows superbuilds (and all the other platforms as desired); given the _5 hour_ build time for merge-win and latest-win, I'd like to reduce these down to 45 mins each as for -DEV since this is causing a backlog on maxquant
- allow use of the jenkins-build scripts to align the jobs with DEV jobs and greatly simplify them
- ease any future backporting by making it compatible with develop
- put the dev_5_1 branch in a good place to leave it in bugfix-only mode

Testing:

Check all the superbuild jobs for 5.1.  They should all be green.  While there are a few changes to look over here, an alternative way to compare is to diff against develop, since this is essentially develop with these changes:
- ome-common component removed (it doesn't exist as a separate component in 5.1)
- gtest component removed (it's embedded in bioformats for 5.1)
- xalan component removed (it's unused)

### CODE REVIEW

**Comment by ghost** [comment]
Note gretzky35 failures in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/197/ are due to https://svn.boost.org/trac/boost/ticket/11856 which leads to a wider question for our platform support:

Do we support CentOS 6 with the Devtoolset-3 compiler, or with the (quite old) base platform.  Or both?  We can apply the patch and keep this going with the base platform, or we can require Devtoolset-3.  On develop we're using Devtoolset-3; on dev_5_1 we're using the base platform (hence the failure).  The fact that this bug exists in the first place indicates that major projects are _not_ testing at all with the base platform.  We need to define a policy here for our support of the platform for 5.1 and 5.2 (which could differ).  Using the base platform will place significant restrictions upon what we can do for 5.2 development, relating to C++11 especially, though a small number of features present in 4.4 could _potentially_ be used.  But the main point I wanted to make here was that we should make a considered decision upon how we support this platform both for 5.1 and for the future.

For this PR we could:
- retain boost-1.59 for 5.1
- apply the 1.60 patch

**Comment by ghost** [comment]
Green in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-win-superbuild/208/ https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/200/

**Comment by sbesson** [comment]
Discussed with @rleigh-dundee and @joshmoore, as we will be disabling the 5.1 CPP jobs post 5.1.8 release to focus on the `develop` line, the impact of these jobs should be limited soon. Given the imminency of the relase and since we have no concrete driver to getting these improvements backported in the maintenance `dev_5_1` line, closing this PR now. We can reopen it for consideration if we need to release a 5.1.9.

**Comment by ghost** [comment]
Note: this change would also require commits bioformats:0569ae3 and bioformats:48c7c856 picking up since the bf-test script is broken and we need the fixes for the jenkins-build integration tests.

**Pull request closed without merging**
