### PR TITLE
glm: Restore package

### PR DESCRIPTION
**Pull request by ghost**
This was removed as part of the refactoring during the decoupling of ome-common back in https://github.com/ome/ome-cmake-superbuild/pull/18/commits .  Now we have a separate ome-qtwidgets package, we can make that selectively depend upon glm, so it's not dragged into all builds (which was the case previously).  The granular dependencies we have now mean it's only going to be built if you are also building ome-qtwidgets.

There changes over the previous version are:
- upgrade to a later point release
- dropping of a patch to a unit test which is now merged upstream and in the new point release
- reworking of the superbuild.cmake structure to match changes to the superbuild logic since the removal, matching other superbuild packages

---

Testing: Run:

```
cmake -G Ninja -Dbuild-packages=glm /path/to/ome-cmake-superbuild
ninja
```

This will build the component in isolation and run its unit tests.  We don't currently build ome-qtwidgets as part of the superbuild CI jobs (it's platform only), but once this is added we can look at enabling it for selected platforms.

### CODE REVIEW

**Comment by mtbc** [comment]
On Debian 8 (stable) this reported encouraging things like,

```
[8/9] Performing test step for 'glm'
```

but then hung. After nearly an hour we investigated and found it stalling at,

```
        Start  20: test-core_func_common

20: Test command: /tmp/build/glm-build/test/core/test-core_func_common
20: Test timeout computed to be: 9.99988e+06
 20/104 Test  #20: test-core_func_common ..............   Passed    0.00 sec
test 21
        Start  21: test-core_func_exponential

21: Test command: /tmp/build/glm-build/test/core/test-core_func_exponential
21: Test timeout computed to be: 9.99988e+06
```

with no further output, it just sits on a core of the CPU. gcc/g++ package is 4:4.9.2-2.

**Comment by mtbc** [comment]
https://www.mail-archive.com/sisyphus-incominger@lists.altlinux.org/msg270009.html may be the same issue?

**Comment by ghost** [comment]
@mtbc I've tested on Windows, MacOS X and Linux (Ubuntu 16.04, 14.04 and Debian 8) and had it pass the tests in all cases.  It might be worth checking if your chroot was using a mix of packages in case some subtle locking issues are due to a glibc/kernel mismatch, or if the chroot is a newer distribution than the base system, glibc might be relying on kernel features which aren't present/functional.

**Comment by mtbc** [comment]
In the chroot the versions are as in [versions.txt](https://github.com/ome/ome-cmake-superbuild/files/250293/versions.txt) under a 3.16.0-4-amd64 kernel.

**Comment by sbesson** [comment]
@mtbc @rleigh-dundee: so what's the status of this PR?

**Comment by ghost** [comment]
@sbesson I've not been able to reproduce Mark's failure on any platform, including the one Mark originally had it on.

**Comment by mtbc** [comment]
I don't seem to have appropriate versions locally for testing: it seems to hit a third-party bug. @rleigh-dundee has tested his own PR successfully. :smiley: Might want someone other than me to follow the instructions.

**Comment by ghost** [comment]
Basically, I think it's mergeable since it works for me on every supported platform.  It's not put into use with this PR, rather it's made available for use by other future PRs.  Logistically, I need it to enable the ome-qtwidgets build, but that work is additional to this and will require PRs across several repos to get it passing and the jenkins slaves providing all the needed bits.

**Pull request merged**
