### PR TITLE
yaml-cpp: New package

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
This adds the `yaml-cpp` library, intended for uses including:

- options API
- integration test metadata (similar to the bioformats INI format, but more extensible and flexible)
- alternative model serialisation format (also potentially useful for testing with the above)
- any places we want human-editable/readable configuration or structure dumping such as test metadata, where we currently use various *ad-hoc* formats like tab-separated values.

Since C++ doesn't have a built in Properties class for file format, YAML would provide a simple and common format which would be simple and extensible for these purposes.  If it turns out to be unsuitable for the options API, it will still likely be useful for testing and other purposes.

This PR doesn't *use* YAML in any respect, it just adds and builds the library so we can investigate the possibilities.

The macro updates and `CMAKE_MODULE_PATH` stuff is to force the use of a newer `FindBoost` in the yaml-cpp build, so it will build with the Boost version provided by the superbuild.

Testing: Check the superbuild jobs are green:

- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-sourcebuild/
- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-superbuild/
- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-win-superbuild/

### CODE REVIEW

**Comment by dgault** [comment]
All the builds are green so the package seems to be integrated ok.

Out of curiosity is there a particular benefit for using YAML over XML or something like JSON?
I haven't had the opportunity to use YAML much before but it seems like it would be suitable for configuration purposes.

**Comment by rleigh-codelibre** [comment]
YAML is a superset of JSON, and it's also a bit more human readable and editable.  For example, it supports comments.  You can use plain JSON and feed it to a YAML parser; so the library would support reading plain JSON for free.  It's also quite a lot more accessible than writing verbose XML, though it doesn't in itself do anything that you couldn't do with XML.  For user-facing stuff, it's likely to be easier for people to use than XML.  It's essentially a potential replacement for Java properties files in the first instance, though we can use it for much more than that in the future.

**Comment by dgault** [comment]
That makes sense to me as it does appear to be more readable from an end users perspective.

**Comment by rleigh-codelibre** [comment]
The other usability point is that it's much easier than JSON to express lists of lists, lists of maps etc. and keep things readable.  http://www.yaml.org/spec/1.2/spec.html has a few examples if you're interested.

**Pull request merged**
