### PR TITLE
Bump Bio-Formats source release to 5.1.7

### PR DESCRIPTION
**Pull request by sbesson**
This should be tested as part of https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/.

### CODE REVIEW

**Comment by ghost** [comment]
The version and hash are correct, and it downloads and builds and passes the tests.  Please merge.

**Comment by sbesson** [comment]
@rleigh-dundee: cannot remember from the top of my HEAD: is this tested via the merge build ?

**Comment by ghost** [comment]
--rebased-to #23

**Comment by ghost** [comment]
@sbesson No.  The merge and latest jobs build from git; only the release build will use this.

**Pull request merged**
