### PR TITLE
boost-1.61: New package

### PR DESCRIPTION
**Pull request by ghost**
Testing: Check build is green.

Putting in breaking to prevent it interfering with the model PRs.  The support was already merged, so this should hopefully just work without any nasty surprises.

### CODE REVIEW

**Comment by ghost** [comment]
Green in https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-breaking/110/ (for CentOS 7).  We would need to move it out of breaking to test every platform, but can wait for the model PRs for the time being.

**Comment by mtbc** [comment]
Pretty sure https://ci.openmicroscopy.org/job/OMERO-DEV-breaking-integration-python/557/testReport/junit/OmeroPy.test.integration.clitest.test_sessions/TestSessions/testLoginAs_rwr____/ is unrelated.

**Comment by mtbc** [comment]
Good to take out of breaking when model PRs are sorted.

**Comment by ghost** [comment]
In merge build: green in

https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-superbuild/248/
https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-win-superbuild/273/

**Comment by mtbc** [comment]
Good to merge.

**Pull request merged**
