### PR TITLE
docs: Use generic graphviz download page URL

### PR DESCRIPTION
**Pull request by ghost**
Don't use the Windows download URL.

### CODE REVIEW

**Comment by mtbc** [comment]
This probably gets staged somewhere? (I'm a bit lost among our contrib CI docs.)

**Comment by ghost** [comment]
https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-docs/BUILD_TYPE=Release,node=marlin/lastSuccessfulBuild/artifact/artefacts/docs/ is where it is at present; having it deployed somewhere is on the todo list.

**Comment by dgault** [comment]
The change looks good to me but the graphviz site is down at the moment so I cant verify the link. Will test again later.

**Comment by dgault** [comment]
The graphviz  site now appears to be back up and the download link is working as expected. PR is good to merge.

**Pull request merged**
