### PR TITLE
Project configuration: Don't propagate derivative path settings

### PR DESCRIPTION
**Pull request by ghost**
Some settings, like `CMAKE_INSTALL_DOCDIR`, contain the project name, and we don't want the contained projects building with bioformats-superbuild in the pathnames.  Likewise the other `_MAN`, `_INFO` etc. variables are all based upon the value of `DATAROOTDIR`, so propagate just this single variable.

---

Other than `tiff` now installing its documentation into a sensible location, there are no major changes here.  None of the removed variables were being set by hand.

### CODE REVIEW

**Comment by sbesson** [comment]
Changes are sensible and builds are still passing. Which file contains the information about the location of the `tiff` documentation?

**Comment by ghost** [comment]
@sbesson Nothing contains that information; it's just making it use the default `$prefix/share/$package` location rather than screwing it up.

**Comment by sbesson** [comment]
Actually just realized https://ci.openmicroscopy.org/job/BIOFORMATS-SUPERBUILD-5.1-merge-push/20/ was not merging the PRs (using Travis status which does not exist on this repo). Modified the merge job so that the merge superbuild jobs can build with this PR included tomorrow.

**Comment by sbesson** [comment]
All jobs being green. :+1:

**Pull request merged**
