### PR TITLE
Refactor superbuild and add glm

### PR DESCRIPTION
**Pull request by ghost**
- Use absolute install paths
- Generate -prerequisites targets to allow independent building of prerequisites and main targets, e.g. `bioformats-prerequisites` is the target to generate the dependencies for `bioformats`
- Boost links correctly against zlib and bzip2 (for compressed stream I/O)
- Update options (add `relocatable-install` for future use by bioformats, remove `bioformats-superbuild` and change the default for `extended-tests`)

---

Rationale:
- glm is a prerequisite for the Qt/OpenGL `ome-qtwidgets` library and viewer; adding this will let the superbuild build the Qt interface
- the refactoring to use absolute install paths is to make the logic simpler, and the addition of further libraries less painful
- the prerequisites targets are to allow easier testing of the superbuild, and to allow the CI jobs to cache the prerequisites to reduce the build time
- the `extended-tests` default change is to also reduce the build time
- the `relocatable-install` option is unused at present, but will be used by https://github.com/openmicroscopy/bioformats/compare/develop...rleigh-dundee:cpp-abspath

---

Testing: all the CI jobs should remain green

### CODE REVIEW

**Comment by ghost** [comment]
--rebased-to #11

**Comment by ghost** [comment]
Green in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/115/ and https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/114/ (115 is a retry of a failing build) and in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-win-superbuild/142/

**Comment by joshmoore** [comment]
@rleigh-dundee : this is against the cmake `develop` branch but the jobs you list are `5.1`. Can you explain?

**Comment by ghost** [comment]
@joshmoore Ah, that's #11 for those jobs.  But these PRs are identical--they are both against the same commit which is where dev_5_1 was branched from.  They are the same commits.

**Comment by mtbc** [comment]
This PR seems good to me; at least, I can't find any problems.

**Comment by mtbc** [comment]
Super-build CI jobs do all seem to be passing.

**Comment by mtbc** [comment]
At least to first seven characters, commit hashes are identical between #10 and #11.

**Comment by ghost** [comment]
Green in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/ and https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/

**Comment by joshmoore** [comment]
i.e. https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/2/ & https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/1/ :thumbsup:

**Pull request merged**
