### PR TITLE
Build separate ome-common

### PR DESCRIPTION
**Pull request by ghost**
- Pick all changes from dev_5_1, including releases and jenkins-build script (#15 #16 #18 #19 #21)
- Revert the reversion of DESTDIR install; this will break bf-test temporarily (will need fixing in a future PR)
- Add `ome-common` as a new package, which `bioformats` depends upon
- Only the last commit is actually new; all the others, including the revert, are from dev_5_1.

---

--rebased-from #15
--rebased-from #18
--rebased-from #19
--rebased-from #21

---

Testing: See the https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/ job

### CODE REVIEW

**Comment by sbesson** [comment]
@rleigh-dundee: thanks for the rebase, can you also mark the matchinig dev_5_1 PRs to simplify the reivew of the additional component in this PR ?

**Comment by ghost** [comment]
@sbesson Done.

**Comment by sbesson** [comment]
@rleigh-dundee: going through this, this PR is the combination of a series of rebases and of the `ome-common` addition right? How easy would it be to have split into 2 parts to simplify the review by the team?

**Comment by ghost** [comment]
@sbesson Yes, it's bringing develop up to date and then dropping ome-common.  It could have been split into two parts, but multiple PRs couldn't have been opened concurrently due to the removal of files being changed.

https://github.com/rleigh-dundee/ome-cmake-superbuild/compare/bd32096d45d0111b38b346e0d9d18f969c1d4874...rleigh-dundee:split?w=1 is the diff of just the ome-common-cpp splitting, ignoring the rebased commits.

**Comment by ghost** [comment]
Green in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/14/console and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/16/console (i.e. now builds on Unix and Windows).

With this we're all done except for the documentation.  There will be some minor tweaking of the exported configuration needed to make it work with external projects and our examples, but that can be done in a future PR as we split out more.

**Comment by sbesson** [comment]
Merging. Thanks @rleigh-dundee.

**Comment by ghost** [comment]
@sbesson Thanks.  By the way, I noticed that when I set the jobs up, they were set to be manually triggered.  Could we make them get triggered the same way the java jobs do?  Not sure which job needs to do that--the trigger job is just for manual triggering?

**Comment by sbesson** [comment]
@rleigh-dundee: I have set up the https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-DEV-merge-trigger/ job to run daily. It can also be triggered manually if needed. We can revisit the needs early January.

**Comment by ghost** [comment]
@sbesson Thanks!

**Pull request merged**
