### PR TITLE
png: Update to version 1.6.21

### PR DESCRIPTION
**Pull request by ghost**
The build is currently failing due to 1.6.19 being removed from the mirrors.  This bumps the version, and the builds should go green again.

---

Testing:
- Verify sha512sum is correct.
- Verify build is green.

### CODE REVIEW

**Comment by ghost** [comment]
https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/85/ is green,
https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/71/ is green.

**Comment by mtbc** [comment]
Good to merge.

**Comment by ghost** [comment]
Note that 1.6.19 is insecure (http://libpng.org/pub/png/libpng.html) so this is also fixing a security vulnerability.

**Comment by ghost** [comment]
--rebased-to #33

**Pull request merged**
