### PR TITLE
bioformats: Fix syntax error in conditional

### PR DESCRIPTION
**Pull request by ghost**
Testing: This triggered the failure in

  https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-CPP-5.1-latest-win-superbuild/VSARCH=x64,VSCONFIG=Debug,VSVERSION=12,label=maxquant-ome/69/console

due to that job being misconfigured and using develop; it wasn't picked up on develop due to the lack of a -latest job.  The fix is trivial; there's a repeated `OR` which shouldn't be there.  The reason it's not picked up by the merge builds is that the conditional terminates early so it doesn't trip up on the bad argument.

### CODE REVIEW

**Comment by sbesson** [comment]
Does this need to be rebased on `dev_5_1` as well?

**Comment by ghost** [comment]
No.

--no-rebase

**Comment by ghost** [comment]
@sbesson Can we merge this please?

**Comment by sbesson** [comment]
Looks sane. I assume this might be confirmed on latest `DEV` jobs eventually.

**Comment by ghost** [comment]
Yes.  We should have one soon; probably when I have time to look at it after 5.1.8 is out.

**Pull request merged**
