### PR TITLE
bioformats: Use 5.1.4-rc1 source release

### PR DESCRIPTION
**Pull request by ghost**
Testing: validate the URL and hash are valid.  This change isn't covered by the -merge or -latest jobs, and will be tested by the -release jobs (which will be finished and tested once this is merged).

### CODE REVIEW

**Comment by ghost** [comment]
@joshmoore Could this be merged today?  It's a blocker for finishing the release jobs, and I only have tonight and tomorrow for that.

**Comment by joshmoore** [comment]
As @melissalinkert mentioned in devteam, we should have a test passing with this change before merging. @sbesson was kind enough to remove the use of `bf-head` in https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/76/ and 3 of 4 have turned green. I'm guessing that the 4th will also pass and then I'll merge. Once you're back, we should discuss that as the more general strategy for the superbuild jobs.

**Comment by joshmoore** [comment]
:thumbsup:

**Comment by ghost** [comment]
@joshmoore With this repository, this was _already tested_ for the bioformats release, both by the -latest-cpp job, and by the -release-cpp job (though https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-release-cpp/ is disabled at present for reasons unknown--this should be testing the source release).  It _will_ be tested by the release job, which was the whole point for having this merged.

If we want to add a second merge build here to test only the stable release, we can do, but it's going to be somewhat redundant and wasteful of CI resources.  This is a different situation than all the existing merge builds, since it's merely aggregating already tested and merged changes.

Just to be clear, I'm referring solely to the use of the bioformats.zip source release here--every other part of the bioformats-superbuild.git repo is tested by the regular -merge and -latest builds.

**Pull request merged**
