### PR TITLE
Replace files with patches

### PR DESCRIPTION
**Pull request by ghost**
Complete the work begun in #56 
- Convert the files copied in `packages/$package/files` to patch files in `packages/$package/patches` for the bzip2, icu and xerces packages
- Add the ability to select Visual Studio version-specific patch sets (used by ICU)
- Each VS version has its own patch file, so they can be added/updated/removed independently
- Add VC14 version of the xerces patchset
- Remove all the files, which is the bulk of this change

---

Testing: Check all builds remain green.  There are no functional changes made here; the result of applying the patches is identical to copying the files, so the files being built are the same as before.

Testing showed that this was also the last bit of VS2015 support to need staging; the OME components required no further changes to build and pass all the tests.  I tweaked the merge build to build with VS2015 in place of VS2012, which will verify this.  See e.g. https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Release,VSVERSION=14,label=maxquant-ome/

### CODE REVIEW

**Comment by ghost** [comment]
Green in
- https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-win-superbuild/232/
- https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-superbuild/209/
- https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-sourcebuild/42/
- https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge/178/

**Comment by joshmoore** [comment]
Change itself & the passing builds all look fine. I'm slightly concerned with "I tweaked the merge build to build with VS2015 in place of VS2012, which will verify this." But assuming we need to finalize that discussion and unify things across the board, merging.

**Comment by ghost** [comment]
What's the concern here?  This verified that the whole collection builds with VS2015.

Regarding support, during the discussion with yourself, Jean-Marie and Jason a couple of months back, regarding limiting the number of platforms, the outcome of that was that we decided to pick VS2013 and VS2015.  The other platforms are still largely undecided, but my understanding was that we had a concrete decision here for Windows.  This PR completes the 2015 support.  I was planning to follow this up with the dropping of 2012 support from the superbuild, since it would reduce the maintenance burden and it's shown by the usage stats I found (on the card) to be the least used version.

**Comment by joshmoore** [comment]
> What's the concern here? This verified that the whole collection builds with VS2015.

The concern is (or was`**`) the communication of what's changing when.  In general, I'd consider what you appended under testing not a "tweak" but rather a change in requirements that should be clear to everyone. That being said, :+1: for updating the card so that we're on the same page.

`**` https://trello.com/c/J8affYoo/11-platform-support-and-build-rationalisation

**Pull request merged**
