### PR TITLE
png: Version 1.6.22

### PR DESCRIPTION
**Pull request by ghost**
This includes my changes for performing proper symbol versioning when building with CMake.  This means that the libpng built by the superbuild will be ABI compatible with a typical distribution- provided libpng.

https://trello.com/c/nd3XXEFI/8-png-symbol-versioning

---

Testing: Verify hash.  Check builds remain green.

### CODE REVIEW

**Comment by mtbc** [comment]
Looks **good to merge**, just waiting for https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-superbuild/ to finish. Do we ignore OME-FILES-CPP-DEV-merge-win-superbuild given that maxquant-ome is offline?

**Comment by mtbc** [comment]
OME-FILES-CPP-DEV-merge-superbuild is green. :+1:

**Comment by ghost** [comment]
@mtbc It does need testing on Windows; I've manually started the job after rebooting the node.

**Comment by mtbc** [comment]
Looks to be taking ages, do feel free to relist for Monday if I forget to check later!

**Comment by mtbc** [comment]
It's been passing! Good to merge.

**Pull request merged**
