### PR TITLE
Add Python dependencies, Boost 1.59 and recursive dependency addition

### PR DESCRIPTION
**Pull request by ghost**
- Add Python dependencies
  - genshi
  - sphinx (including sphinx dependencies)
- Add recursive dependency addition
- Add Boost 1.59 conditionally

Python modules are build dependencies, so are not installed into the "superbuild-install" directory like the other packages.  Instead, they are installed into a "python" directory, and the PATH, PYTHONPATH and CMAKE_PROGRAM_PATH environment variables are set in all downstream package builds to expose the python modules and binaries.  This mirrors the behaviour in the `bioformats-cpp` homebrew formula: https://github.com/Homebrew/homebrew-science/blob/master/bioformats-cpp.rb#L64 which is also used in all other homebrew formulas with python build dependencies.

Recursive dependency addition means that by adding a single target (`ome_add_package`), it will recursively add targets for each of its dependencies, taking care of duplicate dependencies shared between targets.  This mechanism (`ome_add_dependencies` called in a package triggers `ome_add_package`, and so on) will traverse the dependency graph until all dependencies are added.

This is used to conditionally support building with Boost 1.58 (stable, default) or 1.59 (git develop); it substitutes the needed package, and the dependencies automatically resolve.  Previously all dependencies needed including manually up front.  The two boost versions are completely separate directories, i.e. separate packages.  This is to allow changes to one without changing any aspect of the version currently in use by a stable release; this will then be dropped by removing the directory entirely.  While this is currently done for this single package, the infrastructure will allow incompatible changes for any dependency between stable and development releases; if a leaf dependency is changed, this will require dependent packages to be versioned up to the bioformats package to allow the variant versions to be correctly selected.

---

Testing: This will be tested by both superbuild jobs.  You can also test by hand by running `cmake` and then building the `py-genshi` and `py-sphinx` targets.  You should end up with a `python` directory containing the installed files.

```
cmake --build . --config Release --target py-sphinx
cmake --build . --config Release --target py-genshi
```

When the `bioformats` target is built, you'll see it use these modules.  For example `sphinx-build` is set in SPHINX_BUILD in `bioformats-build/CMakeCache.txt`, and this should be under the `python` directory created above.

To test the Boost changes:

```
cmake /path/to/bioformats-superbuild
make help
# Note boost-1.58 in the output

cmake -Dhead=ON /path/to/bioformats-superbuild
make help
# Note boost-1.59 in the output
```

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-CPP-5.1-merge-push-superbuild#63](https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-push-superbuild/63/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-push-superbuild/63/consoleText) for more details.
Possible conflicts:
- PR #7 rleigh-dundee 'boost: Version 1.59'
  - packages/bioformats/superbuild.cmake

**Comment by ghost** [comment]
Windows: Green in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-win-superbuild/117/console

**Comment by ghost** [comment]
Unix: would have gone green in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/94/ had the mac nodes not gone offline sometime around 22:00.  All individual matrix components have now been green at least once.

**Comment by joshmoore** [comment]
This now has conflicts (likely due to the gh-6?)

**Comment by joshmoore** [comment]
@rleigh-dundee : how did this work previously without the Python dependencies?

**Comment by ghost** [comment]
@joshmoore Previously it would have been necessary to have all the python modules manually installed; sphinx was optional, genshi optional depending upon what you were building (git/source zip/dfsg source zip).  This makes it able to always build the documentation and manual pages, and always able to use genshi in all cases.

WRT a merge conflict, I merged in origin/develop without any merge conflicts at all, so I'm not sure why github is complaining.  I've pushed this, it's essentially a no-op!

**Comment by ghost** [comment]
Note I've done test builds of boost 1.58 and 1.59 after develop was merged in, and it's still working just fine.  WRT the merge conflict, both PRs were being successfully sequentially merged by scc for the past week or so, which makes the merge conflict distinctly odd!

**Comment by joshmoore** [comment]
- https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-win-superbuild/125/
- https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/97/

both look quite happy (even if not 100% complete).

**Pull request merged**
