### PR TITLE
LICENSE: Add BSD licence text

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/ome/ome-common-cpp/pull/23

### CODE REVIEW

**Comment by mtbc** [comment]
This really is copyright from 2005? I guess I can see it if moving stuff over from old BF repo.

**Comment by ghost** [comment]
Probably not; I can adjust the ones outside bioformats.

**Comment by ghost** [comment]
I have adjusted the copyright dates to match the work in each repository.

**Comment by mtbc** [comment]
This now looks good to me. :+1:

**Pull request merged**
