### PR TITLE
jenkins-build script fixes

### PR DESCRIPTION
**Pull request by ghost**
This makes the directory structure to copy to the download directory match what we currently have in place.

---

Testing: Check https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/172/ (green) and maybe check any of the completed components in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/173/ if you like (will archive all artefacts to allow verification that it's creating the appropriate structure, e.g. https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/173/BUILD_TYPE=Release,CXXSTD_AUTODETECT=ON,node=gretzky35/artifact/artefacts/).

### CODE REVIEW

**Comment by sbesson** [comment]
One last component relaunched (intermittent failure). Otherwise comparing the output of the last builds of https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-CPP-5.1-latest-superbuild/ and https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-CPP-5.1-merge-superbuild/, the archived artifacts of the latter definitely improve the structure and readability and are inline with the release jobs. Merging once the last matrix job is green.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/174/ :+1:

**Comment by rleigh-dundee** [comment]
@sbesson Final fix for MacOS X.  Now we're just waiting on the CentOS 7 lsb_release installation.

**Comment by ghost** [comment]
--rebased-to #23

**Pull request merged**
