### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Routine updates for boost, hdf5, pybind11 and zlib.  Testing: make sure all builds remain green.

Some additional work to enable VS2017 will be forthcoming in a separate PR.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
hdf5 seems to bring in an updated cmake version requirement (1.10+).  cowfish needs updating.  Note [trello card](https://trello.com/c/l4Be5zg0/45-cowfish-update-cmake-version).

**Comment by rleigh-codelibre** [comment]
https://github.com/ome/ome-files-cpp/pull/95 is a PR to address the Windows failure, but another tweak is likely also required for a separate issue related to uuid/bcrypt.

**Comment by rleigh-codelibre** [comment]
Green in:

- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge/861/
- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-superbuild/937/
- https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-win-superbuild/950/

**Review by mtbc — APPROVED** [review]
Nice that we can clean up patches a bit.

**Pull request merged**
