### PR TITLE
cmake: Improve parallelisation

### PR DESCRIPTION
**Pull request by ghost**
Run subsidiary builds and unit tests in parallel.  This should greatly speed up the build on hosts with sufficient resources (i.e. maxquant, cowfish).

---

Testing: Check builds are green (builds will go red if the systems don't have enough memory).

### CODE REVIEW

**Comment by ghost** [comment]
Shaves 10 mins from the Windows third-party dependency build times:

https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Release,VSVERSION=14,label=maxquant-ome/buildTimeTrend
https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Release,VSVERSION=14,label=maxquant-ome/buildTimeTrend

Less obvious on the other platforms since it's either not parallelised due to only having one processor.  But saves 5 mins on cowfish:

https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/buildTimeTrend

Note we're looking at the difference between the historical max and the current max; the smaller values are with cached third-party deps and are ignored.

**Comment by sbesson** [comment]
@rleigh-dundee: thanks for the additional information as I was going to enquire about the nature of the time variations. If one wanted to get a couple more measurements of the current maximum time while this PR, should `PURGE_CACHE`  be adjusted to `build` to rebuild the third-party deps?

**Comment by ghost** [comment]
@sbesson Yes, that would certainly work.

**Comment by sbesson** [comment]
Run 3 instances of the Windows builds with the `build` cache purger ([323, 324 and 326](https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-win-superbuild/spbr/)).

|  | Release, VS14 | Debug, VS14 | Release, VS12 | Debug, VS12 |
| --- | --- | --- | --- | --- |
| Historical max (without this PR) | 40min (302) | 1h32min (324) | 39min (300) | 1h23min (300) |
| Max clean build time  with this PR | 37 min (324) | 1h34min (302) | 40min (323) | 1h10min (324) |
| Mean clean build time with this PR | 33 min | 1h27min | 34min | 1h10min |

I realized the Windows latest build do not cover the same range of parameters so it is not possible to get similar metrics with build dependencies purging without this PR. Would it be worth extending to compare maximum/median values with the same build conditions with and without this PR?

**Comment by ghost** [comment]
We could, but is it actually worth the effort to do so?  This is a fairly straightforward change, and the reduction in the mean build time for clean builds is fairly clear.  I've verified on my own machine and on maxquant that it's correctly parallelising the boost build and our unit test execution.

**Comment by sbesson** [comment]
Updated my comment to include means build times. While the maximum clean build times with this PR included are not always significant compared to historical maximums, mean values certainly show some overall improvement . Looking at build times for other nodes, there is no obvious build time regression either.

**Pull request merged**
