### PR TITLE
bzip2: Rework cmake build

### PR DESCRIPTION
**Pull request by ghost**
These changes are intended to improve the bzip2 CMake build so that it can be submitted upstream and allow us to drop the patch once it's included in a new upstream release (as we did for libtiff).  It basically cleans it up to use more idiomatic cmake and to generate configuration files to make it easier to link with bzip2 from dependent cmake-using projects.  Since our use of the bzip2 build is solely for boost iostreams at this point in time, we don't make direct use of this configuration data yet.
- Set minimum CMake version to 3.0.0; drop policy settings which are now automatically set.
- Use new form of the `project()` command.
- Lowercase private variable names.
- Remove unnecessary special-casing of the `bzip2recover` binary name.
- Install shell scripts and shell script manual pages only on Unix.
- Add `COMPONENT` to all install commands.
- Minor formatting fixes.
- Use `configure_file(a b COPYONLY)` in place of executing `cmake -E copy`.
- Add CMake configuration, partly autogenerated with a static wrapper to create an imported target and variables for compatibility with `FindBZip2.cmake`.
- Drop trailing `/` after `$ENV{DESTDIR}`.
- Don't pass `-DLIBBZ2=$<TARGET_FILE:bz2>` to `RunTests.cmake` to adjust the `PATH` when running tests; it's not required for bzip2.

Many thanks to Ben Boeckel at Kitware for his suggestions and review of these changes.

/cc @mathstuf

---

Testing: Will be tested by the superbuild; check all superbuild CI jobs remain green.

### CODE REVIEW

**Comment by ghost** [comment]
Green in https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-superbuild/249/ and https://ci.openmicroscopy.org/view/Files-DEV/job/OME-FILES-CPP-DEV-merge-win-superbuild/274/ .

**Comment by ghost** [comment]
Example of differences in packaging:

CentOS 7 (Unix)

```
% ls bin/*b*z*                                                                 
bin/bunzip2  bin/bzcat  bin/bzcmp  bin/bzdiff  bin/bzegrep  bin/bzfgrep  bin/bzgrep  bin/bzip2  bin/bzip2recover  bin/bzless  bin/bzmore
% ls lib/libbz*
lib/libbz2.so  lib/libbz2.so.1.0  lib/libbz2.so.1.0.6
% ls share/man/*/*b*z*
share/man/man1/bunzip2.1  share/man/man1/bzdiff.1   share/man/man1/bzgrep.1        share/man/man1/bzless.1
share/man/man1/bzcat.1    share/man/man1/bzegrep.1  share/man/man1/bzip2.1         share/man/man1/bzmore.1
share/man/man1/bzcmp.1    share/man/man1/bzfgrep.1  share/man/man1/bzip2recover.1
```

VC14 (Windows):

```
% ls bin/*b*z*                                                 
bin/bunzip2.exe  bin/bzcat.exe  bin/bzip2recover.exe
bin/bz2.dll      bin/bzip2.exe
% ls lib/*bz*  
lib/bz2.lib
% ls share/man/*/*b*z*                                         
share/man/man1/bunzip2.1  share/man/man1/bzcat.1  share/man/man1/bzip2.1  share/man/man1/bzip2recover.1
```

So all as expected.  The shell scripts and corresponding manpages are intentionally absent on Windows.

One minor consideration is whether to retain the binary manpages on Windows or not.  I've kept them for now since they are the only form of documentation.

**Comment by sbesson** [comment]
Looking at the diff between the merge and latest builds of ome-files on Unix and Windows

```
sbesson@ls30630:Downloads $ diff -rn ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64 ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251 | grep bz | grep -v Search
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/bin/bzcat and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/bin/bzcat differ
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/bin/bzip2 and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/bin/bzip2 differ
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/bin/bzip2recover and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/bin/bzip2recover differ
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/bin/bzcat and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/bin/bzcat differ
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/bin/bzip2 and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/bin/bzip2 differ
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/bin/bzip2recover and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/bin/bzip2recover differ
Only in ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/lib: libbz2.a
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/lib/libbz2.so and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/lib/libbz2.so differ
Only in ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/lib: libbz2.so.1
Only in ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/lib: libbz2.so.1.0
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/lib/libbz2.so.1.0.6 and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/lib/libbz2.so.1.0.6 differ
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/cowfish/build/superbuild-install/lib/libz.so;/usr/lib64/libm.so"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/cowfish/build/superbuild-install/lib/libz.so;/usr/lib64/libm.so"
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/build/lib/libz.a and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/lib/libz.a differ
Only in ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/share/man/man1: bzcat.1
Only in ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/build/share/man/man1: bzip2recover.1
Only in ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/lib: libbz2.a
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/lib/libbz2.so and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/lib/libbz2.so differ
Only in ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/lib: libbz2.so.1
Only in ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/lib: libbz2.so.1.0
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/lib/libbz2.so.1.0.6 and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/lib/libbz2.so.1.0.6 differ
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/cowfish/build/superbuild-install/lib/libz.so;/usr/lib64/libm.so"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/cowfish/build/superbuild-install/lib/libz.so;/usr/lib64/libm.so"
Binary files ome-files-standalone-bundle-0.1.1-6-gedc3a13-Release-CentOS7.2-x86_64/lib/libz.a and ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/lib/libz.a differ
Only in ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/share/man/man1: bzcat.1
Only in ome-files-standalone-bundle-0.1.1-9-g37267bd-Release-CentOS7.2-x86_64-b251/share/man/man1: bzip2recover.1
sbesson@ls30630:Downloads $ diff -ur ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276 | grep bz | grep -v Search
Binary files ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin/bz2.dll and ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276/bin/bz2.dll differ
Binary files ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin/bzcat.exe and ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276/bin/bzcat.exe differ
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin: bzcmp
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin: bzdiff
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin: bzegrep
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin: bzfgrep
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin: bzgrep
Binary files ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin/bzip2.exe and ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276/bin/bzip2.exe differ
Binary files ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin/bzip2recover.exe and ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276/bin/bzip2recover.exe differ
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin: bzless
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/bin: bzmore
Binary files ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/lib/bz2.lib and ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276/lib/bz2.lib differ
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/lib: bz2static.lib
Only in ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276/share/man/man1: bzcat.1
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/share/man/man1: bzcmp.1
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/share/man/man1: bzdiff.1
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/share/man/man1: bzegrep.1
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/share/man/man1: bzfgrep.1
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/share/man/man1: bzgrep.1
Only in ome-files-bundle-0.1.1-9-g37267bd-VC12-x64-Release-b276/share/man/man1: bzip2recover.1
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/share/man/man1: bzless.1
Only in ome-files-bundle-0.1.1-8-gfbce5fc-VC12-x64-Release/share/man/man1: bzmore.1
```

So the packaging matches the description of the changes. Do we have a reference for the upstream submission and is it still in `next`?

**Comment by ghost** [comment]
The file changes there all look fine.

It's not been submitted upstream yet (to bzip.org).  Since the upstream author has no public bug tracker, version control or anything except an email address, there won't be any reference for it.  I'll CC you on the email when I send it.  I'll wait until it's merged before doing this, so we have somewhere to point at for the final version.

**Comment by ghost** [comment]
@sbesson Please could we merge this?

**Pull request merged**
