### PR TITLE
Allow disabling of third-party dependencies

### PR DESCRIPTION
**Pull request by ghost**
- build-cache option allows re-use of an earlier build (installed dependencies)
- python-cache option allows re-use of an earlier build (python build dependencies)
- split third-party and first-party dependencies; build-prerequisites option allows disabling of all third-party dependencies; first-party dependencies is currently bioformats only, but in the future can be extended to multiple components

This change is to reduce build time by omitting the building of all third-party prerequisites for every CI build. Reuse of a previous build's prerequisites is achived by adding the build-cache and python-cache options to specify the location of the previous build's installed and internal dependencies (the python dependencies are not installed since they are only used for source and documentation generation).  Coupled with build-prerequisites, to disable the third-party prerequisites, this allows a build to only build bioformats and skip all third-party source builds.

I originally implemented all this logic in the jenkins job, but it's cleaner to have it here; it's not something an end user will need, but isn't used by default and can be ignored entirely.  The existing logic to allow skipping the building of certain components had also never been tested in this way and was buggy; this change also corrects that (`ome_add_empty_project` and removal of unnecessary `if(${CMAKE_PROJECT_NAME}_USE_SYSTEM_${EP_PROJECT})` blocks).

---

Testing: will be tested by the CI jobs with appropriate adjustment of the job logic.  https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/122/ (#124) will cache the dependencies.  #125 will then use these and build in a fraction of the time.  Both jobs should be green.

### CODE REVIEW

**Comment by joshmoore** [comment]
Times from https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/BUILD_TYPE=Debug,CXXSTD_AUTODETECT=OFF,node=mackerel/buildTimeTrend don't look to be dropping. Any thoughts?

screen shot 2015-11-02 at 11 41 05

**Comment by ghost** [comment]
Yes, the job conditional to check if the merge build has changed is always telling us it changed.  This is due to SCC merge commits having both multiple commits and a new timestamp and generated commit message.  I'll need to update it to use the tree rather than the commit, and also to save the tree hash so we have a basis for comparison.

This is an issue with the job configuration, rather than the PR itself.

**Comment by ghost** [comment]
@joshmoore Job updated to use `%T` rather than `%H` and to store the tree hash in the cache.  Rerunning now.  Once it's complete then a subsequent rebuild should then take less time.

**Comment by ghost** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/140/

Also, see the trends for the individual nodes in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/ (click on node in matrix, click on trend).  For Debug builds, times are 2/3 to 1/2 of previous; for Release builds are 1/4 to 2/3--the release builds run more tests which are very slow on some platforms--we can further tweak the job to reduce this).

Note one build failed, but this wasn't a fault of this PR or the job; the workspace of the last matrix component was for some reason deleted while the job was running the unit tests.  This build was green the previous day.

**Comment by joshmoore** [comment]
I assume the same logic hasn't yet been applied to Windows? Is it going to be straight-forward or require further investigation?

screen shot 2015-11-10 at 10 18 09

**Comment by ghost** [comment]
In terms of this PR, no further changes are necessary.  In terms of the Windows job, we need to redo the super build shell logic in a batch file, which will be horrible, but which should be possible.  The main annoyances will be lack of `$()` to get the tree hashes (there's a workaround) and doing a selective deletion of the workspace contents (the clean workspace plugin is buggy).

**Comment by joshmoore** [comment]
Oh dear. Alright. Merging this, and cross-fingers on the `.bat` front!

**Comment by ghost** [comment]
--rebased-to #16

**Pull request merged**
