### PR TITLE
Add build script to replace Jenkins logic

### PR DESCRIPTION
**Pull request by ghost**
- Move Jenkins job shell blocks into a script for easier testing and maintenance
- Fix issues resulting in a buggy and bloated tarfile on CentOS (FindBoost detecting system boost erronously and brokenly, and building a set of unwanted static libs)
- Platform naming is now taken directly from the platform, and does not require hardcoding of CPP_OSNAME on each build node
- Also tests that the build archive has basic functionality after the build is done, i.e. a basic sanity check, doing some of what's in our testing docs.

---

Testing: Tested by https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/ which should be green in the morning.

It's also testable by design outside jenkins.  To do that, you'll need to create a temporary work directory and run something like:

```
./ome-cmake-superbuild/scripts/jenkins-build -w $(/bin/pwd) -s $(/bin/pwd)/ome-cmake-superbuild -j 4
```

`-w` specifies the workspace, i.e. the temporary work directory; -s specifies the source directory, i.e. the path to the `ome-cmake-superbuild` git repo.  If you're wanting to build bioformats.git in place of the 5.1.6 source release, then clone it into a `bioformats` directory in the work directory, and add a `-G` option, optionally with a `-g` option to specify the branch if not HEAD.  There are a number of other options to customise the build if desired, use `-h` to list them.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [BIOFORMATS-CPP-5.1-merge-push-superbuild#127](https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-push-superbuild/127/). See the [console output](https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-push-superbuild/127/consoleText) for more details.
Possible conflicts:
- PR #17 rleigh-dundee 'Revert absolute path usage for glm build'
  - helpers/cmake_configure.cmake
  - packages/bioformats/superbuild.cmake

**Comment by joshmoore** [comment]
Watching https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-CPP-5.1-merge-superbuild/166/console closely. Big :thumbsup:

(For reference, here's the invoking Jenkins block:

```
EXTENDED_TESTS=
if [ "$BUILD_TYPE" = "Debug" ]; then
  EXTENDED_TESTS=-e
fi

CMAKE_VERBOSE=
if [ "$VERBOSE" = "true" ]; then
  CMAKE_VERBOSE=-v
fi

if [ -d /usr/local/opt/qt5/bin ]; then
  PATH="/usr/local/opt/qt5/bin:$PATH"
fi

if [ -f /opt/rh/python27/enable ]; then
  source /opt/rh/python27/enable
elif [ -f $HOME/virtualenv/bin/activate ]; then
  source $HOME/virtualenv/bin/activate
fi


superbuild/scripts/jenkins-build ${EXTENDED_TESTS} ${CMAKE_VERBOSE} -w "$WORKSPACE" -s "${WORKSPACE}/superbuild" -G -g "scc/$PUSH_BRANCH" -p "$PURGE_CACHE"

```

)

**Comment by ghost** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/166/ is green
https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/167 is running now and will test the build with the cache present.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/168/ in progress

**Comment by ghost** [comment]
@sbesson The failure of #167 looks like it was due to the workspace being purged across all nodes for all matrix components while the job was still in progress.  Was this triggered manually by anyone?  This isn't the first occurence of this failure.  It's clear that the PR works on every platform with and without the build cache though.

**Comment by sbesson** [comment]
@rleigh-dundee: given the timestamp of the failures (00:58), I would not suspect a workspace cleanup would have been triggered manually. I will have a look at the console logs.

**Comment by ghost** [comment]
@sbesson Thanks.  I don't see anything obvious in the logs for the matrix components, as for the previous time this happened, but from the errors it's quite clear that the workspace contents were removed somehow while the job was running--e.g. the unit tests fail due to the test programs themselves not existing.  They were built earlier in the job, and the job itself wouldn't be deleting them, so some external factor must have caused it.

**Comment by sbesson** [comment]
Looking further in the console logs, it looks like we are hitting https://issues.jenkins-ci.org/browse/JENKINS-27329.

**Comment by ghost** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/168/ is green.  Could this be merged?

**Comment by joshmoore** [comment]
As mentioned in devteam, I didn't get a chance to go over the options in detail, but :thumbsup: in terms of now having a script we can all review and discuss together. Merging.

**Comment by ghost** [comment]
--rebased-to #23

**Pull request merged**
