### PR TITLE
Generate documentation contents page

### PR DESCRIPTION
**Pull request by ghost**
Add a top-level contents page.  Build by default with the jenkins build script, but not with a manual build (since we don't want to pollute `share/doc` with junk for non-packaged builds).

Testing: Check `share/doc` in a binary build and the staging docs.  It should contain an `index.html` which has pointers to the various manuals and API references.

Check http://www.openmicroscopy.org/site/support/ome-files-cpp-staging/ for the live version.

### CODE REVIEW

**Comment by ghost** [comment]
Note that the docs archive created on Windows is for some reason showing empty for me; not sure what's up there.  We don't publish this one and we can fix it later; getting the contents for the published copy was the main point of this change.

**Comment by ghost** [comment]
The Windows issue with the zip should be fixed with the last commit--it was using an absolute path when packing.

**Comment by ghost** [comment]
Windows docs: https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Release,VSVERSION=12,label=maxquant-ome/lastSuccessfulBuild/artifact/artefacts/docs/

Default published docs: https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-docs/BUILD_TYPE=Release,node=marlin/lastSuccessfulBuild/artifact/artefacts/docs/

**Comment by dgault** [comment]
Artifact's from the standard and Windows superbuild appear to be correct and as expected. The index page is present and the links are working and correct. The API links appear blank as doxygen is not installed so this is as expected.

PR looks good to merge.

**Pull request merged**
