### PR TITLE
Documentation link checking and packaging

### PR DESCRIPTION
**Pull request by ghost**
- Enable link checking in subsidiary builds; this is done when doxygen is enabled (otherwise the links won't exist)
- Package sphinx and doxygen docs in a single bundle, since they are all interlinked

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Note that there's now a zip documentation bundle in addition to the tar.gz.

**Comment by ghost** [comment]
Green in https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-docs/12/

**Comment by ghost** [comment]
@dgault If you wanted to briefly check the contents of https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-docs/BUILD_TYPE=Release,node=marlin/lastSuccessfulBuild/artifact/artefacts/docs/ (same as for the other build), that should be sufficient to confirm everything is OK.

**Comment by dgault** [comment]
The renamed  bundles and the new zip file all look to be correct and working in the latest build. Is there any way to test that the links checking has worked correctly? I couldn't find any references to it in the console out

**Comment by ghost** [comment]
The build this morning failed, so there was nothing at that point to check (though what is there now is essentially unchanged other than the addition of the zip)

The build fails if the link checking fails, so that it being green now confirms this.  The output in

https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-docs/BUILD_TYPE=Release,node=marlin/lastSuccessfulBuild/artifact/build/ome-files-build/docs/sphinx/linkcheck/output.txt
https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-docs/BUILD_TYPE=Release,node=marlin/lastSuccessfulBuild/artifact/build/ome-cmake-superbuild-docs-build/linkcheck/output.txt

shows the link checks; it will say if any are failed.

**Comment by dgault** [comment]
The output from those look good and since the build is green then PR looks good to merge

**Pull request merged**
