### PR TITLE
Fix GTest on Windows

### PR DESCRIPTION
**Pull request by ghost**
Due to the needlessly unusual and restrictive requirements of GTest, on Windows in particular, the way we split it out of bioformats in the recently merged ome-common split work was fine on every platform except for Windows.  This PR, and the corresponding PRs for ome-common and bioformats, rectify this.  Essentially, they make the gtest build work exactly as it did when embedded in bioformats, except that the gtest source is downloaded by the superbuild and then built inside each project which requires it.  This means it's downloaded once, but needs building multiple times.  It's not ideal, but it's the only way to make this stuff work on Windows...
- Download gtest only; don't build it
- Pass the location of the gtest source to projects using it
- ome-common and bioformats then build it as part of their build; see https://github.com/ome/ome-common-cpp/pull/2 and https://github.com/openmicroscopy/bioformats/pull/2157

---

Testing:
- builds should remain green
- verify that the tests run for ome-common and bioformats in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/ and especially in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/ (currently gtest isn't found and the Windows tests are not built or run, so the difference is quite obvious)

### CODE REVIEW

**Comment by ghost** [comment]
The job didn't trigger automatically; started manually.

**Comment by sbesson** [comment]
Apologies @rleigh-dundee, the cron trigger was set up to run on Sundays... I fixed it so that it runs Mon-Fri as expected now. Let's check  it has been triggered automatically tomorrow.

**Comment by ghost** [comment]
See https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Debug,VSVERSION=12,label=maxquant-ome/17/consoleText .  `curl -s https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Debug,VSVERSION=12,label=maxquant-ome/17/consoleText | grep "\[  PASSED  \]"`.  For Unix https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/15/consoleText (and the other debug/release build for each).  All the builds are green and contain the test results.

**Comment by sbesson** [comment]
Thanks @rleigh-dundee. Will have a look today or tomorrow at latest. Since the console log is so big to digest, is it possible to store the gtest output as an XML that could also be consumed by the Jenkins Junit plugin ?

**Comment by ghost** [comment]
@sbesson Unfortunately not directly at present.  It can output XML, but it's not in a form consumable by that plugin (I think--it's a while since I last looked into this).  I can certainly look into it again.  Maybe there's a different plugin for it.  We could also get the build results sent to the ctest dashboard--e.g. the one at https://open.cdash.org/index.php -- this is the CTest output from cmake, rather than the GTest output from the individual tests themselves.

**Comment by ghost** [comment]
@sbesson Looks like you can run the tests with `--gtest_output=xml:results.xml` and get something the junit plugin can use.  But it'll need doing on another PR--we'll need to adjust the tests to use the option, and then the jobs to find the output.  There might be additional caveats--some people mentioned the need to do additional manging of the data so that the plugin can parse it; it apparently has some expectations of how it's structured on top of it being valid...

**Comment by sbesson** [comment]
Tested using the merge build link indicated above. The [build time](https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/buildTimeTrend) is certainly extended  with this PR included and parsing the log file indicates PASSED tests while the [previous build](https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/16/) has no mention of them. So this PR and its companion ones is working functionally.

However, I was unable parse the console log directly from a Web browser without freezing it. After downloading them I realized the log increased from 19M to 359M per matrix component on Windows. Additionally the Unix builds (unlike all other builds in the organization) are currently preserving only the last 5 builds meaning that we lose the history, logs and time trend of all previous builds. This certainly highlights more general concerns about these build and their usability by team members reviewing C++ PRs at the moment. 

Let put this PR (and other C++ PRs) on hold as everyone is going away and schedule some time to discuss the structure and usability of these CI builds when people are back.

**Comment by ghost** [comment]
The log issue was already present.  Could we merge this and fix it separately, please.  Otherwise we have zero testing.

The issue is in logging--it's dumping the schemas to stdout on windows.  We can open a PR to resolve that independently.

**Comment by ghost** [comment]
See https://github.com/ome/ome-common-cpp/pull/5 and https://github.com/openmicroscopy/bioformats/pull/2166 .  This reduces the log size on Windows.

**Comment by mtbc** [comment]
Log size is indeed more reasonable on recent builds and tests do seem to be running.

**Comment by mtbc** [comment]
This PR and its kin (see description for links) seem good to merge to me. The outcomes in CI look good and the diffs look reasonable.

**Pull request merged**
