### PR TITLE
bzip2: cmake patch: Add missing COMPONENTS to install calls

### PR DESCRIPTION
**Pull request by ghost**
Minor fixes for final cleanup before upstream submission.

Testing: Check builds are green.

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
--breaking

It's not breaking, but it's not for the 0.2.0 release.

**Comment by dgault** [comment]
The changes look good to me and the breaking builds look to be good also. I assume this is staying in breaking for now then?

**Comment by ghost** [comment]
No, it was just in breaking to avoid any pre-release breakage in the merge build.  I'll remove the breaking label now we know it's OK.

**Comment by dgault** [comment]
Builds are green with this included. Is there anything can be tested to confirm the missing components fix?

**Comment by ghost** [comment]
Nothing to test--it's correct both with and without since we don't ourselves use the component classification--we always install everything.  This is more something that's useful with other build systems which I wanted to be correct for upstream submission of the patch.

**Comment by dgault** [comment]
In that case the change is good with our builds and should be fine to merge.

**Pull request merged**
