### PR TITLE
tiff: Version 4.0.9

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
New upstream release, with a lot of security fixes.  [Changes](http://www.simplesystems.org/libtiff/v4.0.9.html): a bunch of build fixes and testing stuff by me, and a huge amount of overflow and other bugs fixed as a result of fuzzing and static analysis.

Testing: Builds should remain green.

### CODE REVIEW

**Comment by mtbc** [comment]
Looks to be in latest push:
```
Calling 'git merge --no-ff -m merge master -Dorg -Snone: PR 172 (tiff: Version 4.0.9) 928737d67dd719d91b05208ac1fd64007d039b78'
```

**Comment by mtbc** [comment]
https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Release,VSVERSION=14,label=maxquant-ome/ is failing.

**Comment by mtbc** [comment]
Diff looks good.

**Comment by rleigh-codelibre** [comment]
The Windows failure is due to python/pip, unrelated to this PR.  I'm looking at that right now.

**Review by mtbc — APPROVED** [review]

**Pull request merged**
