### PR TITLE
Refactor superbuild and add glm (5.1)

### PR DESCRIPTION
**Pull request by ghost**
- Use absolute install paths
- Generate -prerequisites targets to allow independent building of prerequisites and main targets, e.g. `bioformats-prerequisites` is the target to generate the dependencies for `bioformats`
- Boost links correctly against zlib and bzip2 (for compressed stream I/O)
- Update options (add `relocatable-install` for future use by bioformats, remove `bioformats-superbuild` and change the default for `extended-tests`)

---

Rationale:
- glm is a prerequisite for the Qt/OpenGL `ome-qtwidgets` library and viewer; adding this will let the superbuild build the Qt interface
- the refactoring to use absolute install paths is to make the logic simpler, and the addition of further libraries less painful
- the prerequisites targets are to allow easier testing of the superbuild, and to allow the CI jobs to cache the prerequisites to reduce the build time
- the `extended-tests` default change is to also reduce the build time
- the `relocatable-install` option is unused at present, but will be used by https://github.com/openmicroscopy/bioformats/compare/develop...rleigh-dundee:cpp-abspath

---

Testing: all the CI jobs should remain green

### CODE REVIEW

**Comment by ghost** [comment]
--rebased-from #10

**Comment by joshmoore** [comment]
See https://github.com/ome/ome-cmake-superbuild/pull/10#issuecomment-151780437 and https://github.com/ome/ome-cmake-superbuild/pull/10#issuecomment-151796947 for sign-off.

**Comment by joshmoore** [comment]
I take that back. It doesn't look like this PR has been built-green yet. @rleigh-dundee?

**Comment by ghost** [comment]
@joshmoore CI status:

Green in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/115/ and https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/114/ (115 is a retry of a failing build on perch) and in https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-win-superbuild/142/

9932b06fcf3d6e05379572c6ba3e2b3ffa165a94 - win 141
9932b06fcf3d6e05379572c6ba3e2b3ffa165a94 - unix 114
9932b06fcf3d6e05379572c6ba3e2b3ffa165a94 - perch rebuild in 115

**Comment by joshmoore** [comment]
So my confusion:
- https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-push-superbuild/88/console merges develop
- https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-push-superbuild/89/console merges dev_5_1

This changed in the background I assume?

**Comment by ghost** [comment]
@joshmoore It was fixed yesterday by @sbesson.  These PRs are tested against the 5.1 scc merge (though at present they are one and the same with develop).  Initially, @sbesson pushed the develop merge onto the 5.1 branch so we could run the jobs, but we later re-ran it so it used the new 5.1-specific PR.

**Comment by joshmoore** [comment]
Thanks for the info. Probably good to have a discussion about all this once 5.2.0 testing has settled down.

**Pull request merged**
