### PR TITLE
docs: Correct qt5 package names

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
https://trello.com/c/8tuKTj8A/12-debian-package-name-fix-for-ome-files

/cc @mtbc 

The original names had hyphens in the names which should not have been present.

Testing: Check the package names are correct.

### CODE REVIEW

**Comment by mtbc** [comment]
How do I stage this locally? Struggling slightly with http://downloads.openmicroscopy.org/ome-files-cpp/0.2.1/13/docs/ome-files-bundle-docs-0.2.1-b13/ome-cmake-superbuild/manual/html/building.html.

**Comment by sbesson** [comment]
@mtbc this is staged at https://www.openmicroscopy.org/site/support/ome-files-cpp-staging. NB: this is something we could also add to https://www.openmicroscopy.org/site/support/contributing/ci-ome-files.html#term-ome-files-cpp-dev-merge-docs

**Comment by mtbc** [comment]
Good to merge.

(Outwith this PR: it's inconvenient to have the useful package names sprinkled across so many little pages.)

**Comment by hflynn** [comment]
N.B. opened a PR to add the staging address to the CI docs

**Pull request merged**
