### PR TITLE
CMake module updates

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Routine updates for two Find modules

- Update FindBoost for Boost 1.68.
- Update XercesC for Xerces 3.2.x

Both are taken from the upstream master branch.

Testing: Check builds remain green.

/cc @joshmoore

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
@sbesson With the last commit, the Windows job should return to normal.

**Comment by rleigh-codelibre** [comment]
@sbesson Please could you delete the whole workspace for `OME-FILES-CPP-DEV-merge-win-superbuild` and retry running the C++ jobs?  The error remaining in [the latest build](https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-win-superbuild/VSARCH=x64,VSCONFIG=Release,VSVERSION=14,label=maxquant-ome/1040/console) is a broken build cache, so wiping out the workspace should resolve the inconsistency.  The last commits pushed here should also update Boost to the current version and fix the bzip2 download which would otherwise have broken the build.

Regards,
Roger

**Comment by rleigh-codelibre** [comment]
Hmm, it's still failing this morning.  Would anyone be able to provide a list of the boost libraries in `build/stage/lib` or `cache/.../lib` so I could see what's not right here?  (The workspace isn't public.)

**Comment by joshmoore** [comment]
I don't think a clean workspace was tried yesterday, but I did just now and it failed again. I've attached a screenshot of cache/build/lib. I don't see a `build/stage/lib`.

screen shot 2018-08-14 at 12 37 09

**Comment by rleigh-codelibre** [comment]
Thanks.  Looks exactly like what I see locally (where it works just fine…).  The problem must lie elsewhere.

**Comment by rleigh-codelibre** [comment]
Copied to [GitLab](https://gitlab.com/codelibre/ome-cmake-superbuild/merge_requests/189)

**Comment by sbesson** [comment]
Closing as per announcement on the [OME mailing list](http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2018-August/004294.html). For those interested, please refer to this [set of repositories](http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2018-November/004308.html).

**Pull request closed without merging**
