### PR TITLE
pybind11 2.2.1

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Update to 2.2.1 for PYBIND11_MODULE macro (replaces PYBIND11_PLUGIN).

### CODE REVIEW

**Comment by mtbc** [comment]
Which CI checks this works okay?

**Comment by rleigh-codelibre** [comment]
https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/766/consoleFull shows the build (half way through the log).

It fails later for unrelated reasons which will require another separate PR.

**Review by mtbc — APPROVED** [review]
Good to go once https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-superbuild/ is green.

**Comment by sbesson** [comment]
This change matches the version required by the changes in https://github.com/ome/ome-files-py/pull/25/ and the version installed in https://github.com/ome/ome-files-py/blob/master/Dockerfile.c7 and https://github.com/ome/ome-files-py/blob/master/Dockerfile.u1604 and used by Travis for building.

Moving forward, this raises the question on whether we should cap the version of `pybind11` in `ome-files-py` as well to express the build requirements and bump in both places when we need a new version.

**Comment by rleigh-codelibre** [comment]
I don't think a *cap* is required; this is raising the minimum version rather than limiting to a maximum version.

**Comment by joshmoore** [comment]
Thanks, guys.

**Pull request merged**
